### ISSUE TITLE
Whats wrong?

### ISSUE THREAD

**Issue by scriptxd** [xtekky/TikTok-ViewBot#45]
Even u cant fix problem,  u Should remove this git....

 closed issues without fixing...  🤨
Still captcha invalid etc.....

**Comment by xtekky** [comment]
haha, shut bro I can fix the problem because I ain't a skid but there is something called having a social life and scholl, something u prolly don't have so u can't understand, I don't have the time to dev like a discord mod and to volunteer, I'll be updating the repo but not now because I don't have time.
